### ISSUE TITLE
How to use FFmpeg?

### ISSUE THREAD

**Issue by Xiarno** [emlun/factorio-replay-timelapse#1]
Each time I try, I get a jumbled mess. See video.
https://user-images.githubusercontent.com/24660485/215936602-a3d44daf-02c4-4d60-a4ab-3262bebfd680.mp4

My images are alright too.
![00000241-base](https://user-images.githubusercontent.com/24660485/215936643-7acd3c3e-5902-416b-afb6-272984b7edf0.png)

The command I use is: `ffmpeg -i %08d-base.png output.mp4`

**Comment by Xiarno** [comment]
Wait what, the video looks fine on Github but not when I watch it from my computer?!??!

**Comment by emlun** [comment]
It looks fine for me too in Chrome, but Firefox fails to play it, claiming it's corrupt. I've also sometimes had issues with VLC stuttering during playback of local files (not just these timelapses). I don't know why.

Sorry, I don't know what's causing this, your command looks fine to me as far as I remember. You'll have to turn to ffmpeg support channels for further help.
